# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-concrete' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxAlamofire'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'Action'
  pod 'Kingfisher', '~> 4.0'
  
  target 'desafio-concreteTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
  end
  
end
