# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def testing_pods
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'RxBlocking', '~> 4.0.0'
end

target 'desafio-concrete' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.5.1'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxAlamofire', '~> 4.0.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0.2'
  pod 'Action', '~> 3.4.0'
  pod 'Kingfisher', '~> 4.0'
  
  target 'desafio-concreteTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end
  
end
